In [2]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_excel("data/상가(상권)정보_20200221/상가업소정보_201912_02.xlsx")
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19917773,대구통닭,통통치킨상인2호점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2.729012e+24,NaN,대구광역시 달서구 상화북로43길 74,704370.0,42806.0,NaN,1,NaN,128.546040,35.817554
1,19919475,빵마루,NaN,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,2.726011e+24,녹원아파트,대구광역시 수성구 무학로 187,706090.0,42183.0,NaN,1,NaN,128.628821,35.830867
2,19925178,오구피자,NaN,Q,음식,Q07,패스트푸드,Q07A01,피자전문,I56192,...,2.817011e+24,NaN,인천광역시 남구 미추홀대로 541,402200.0,22216.0,NaN,1,NaN,126.678585,37.445680
3,19907335,명진가마솥오곡밥,NaN,Q,음식,Q01,한식,Q01A16,보리밥전문,I56111,...,2.920012e+24,NaN,광주광역시 광산구 첨단중앙로170번길 17,506303.0,62274.0,NaN,1,NaN,126.842826,35.220843
4,19909700,이오쇠고기국밥,NaN,Q,음식,Q01,한식,Q01A05,해장국/감자탕,I56111,...,2.711016e+24,NaN,대구광역시 중구 달구벌대로 2222,700430.0,41951.0,NaN,NaN,NaN,128.606083,35.862251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528306,16314214,A모텔,NaN,O,숙박,O02,모텔/여관/여인숙,O02A01,모텔/여관/여인숙,I55112,...,2.714010e+24,NaN,대구광역시 동구 동부로22길 27,701827.0,41243.0,NaN,NaN,NaN,128.627103,35.874158
528307,16292329,하얀기쁨,NaN,F,생활서비스,F02,세탁/가사서비스,F02A01,세탁소/빨래방,S96912,...,3.020015e+24,더리치타운,대전광역시 유성구 관평1로 15,305509.0,34017.0,NaN,1,113,127.387018,36.425895
528308,16292506,쭈네일,NaN,F,생활서비스,F01,이/미용/건강,F01A02,발/네일케어,S96119,...,3.611010e+24,스타힐타워2,세종특별자치시 세종특별자치시 한누리대로 2129,339008.0,30150.0,2,NaN,2,127.289760,36.478573
528309,16394366,효소먹은돼지,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2.920012e+24,NaN,광주광역시 광산구 풍영로200번길 13,506304.0,62225.0,NaN,NaN,NaN,126.815130,35.189369
528310,16335149,더칼라네일&속눈썹,NaN,F,생활서비스,F01,이/미용/건강,F01A02,발/네일케어,S96119,...,2.729011e+24,NaN,대구광역시 달서구 당산로 27,704912.0,42676.0,NaN,NaN,NaN,128.544277,35.839861

In [17]:
df = df.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528311 entries, 0 to 528310
Data columns (total 39 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     528311 non-null  int64
 1   상호명        528311 non-null  object
 2   지점명        63168 non-null   object
 3   상권업종대분류코드  528311 non-null  object
 4   상권업종대분류명   528311 non-null  object
 5   상권업종중분류코드  528311 non-null  object
 6   상권업종중분류명   528311 non-null  object
 7   상권업종소분류코드  528311 non-null  object
 8   상권업종소분류명   528311 non-null  object
 9   표준산업분류코드   496133 non-null  object
 10  표준산업분류명    496133 non-null  object
 11  시도코드       528311 non-null  int64
 12  시도명        528311 non-null  object
 13  시군구코드      528311 non-null  int64
 14  시군구명       528311 non-null  object
 15  행정동코드      528311 non-null  int64
 16  행정동명       528311 non-null  object
 17  법정동코드      528311 non-null  int64
 18  법정동명       528311 non-null  object
 19  지번코드       528311 non-null  int64
 20  대지구분코드     528311 non-null  int64
 21  대지구분명      528311 non-null  object
 22  지번본번지      528311 non-null  int64
 23  지번부번지      428134 non-null  float64
 24  지번주소       528311 non-null  object
 25  도로명코드      528311 non-null  int64
 26  도로명        528311 non-null  object
 27  건물본번지      528311 non-null  int64
 28  건물부번지      84804 non-null   float64
 29  건물관리번호     528311 non-null  float64
 30  건물명        171082 non-null  object
 31  도로명주소      528311 non-null  object
 32  구우편번호      528248 non-null  float64
 33  신우편번호      528295 non-null  float64
 34  동정보        52436 non-null   object
 35  층정보        247826 non-null  object
 36  호정보        93625 non-null   object
 37  경도         528311 non-null  float64
 38  위도         528311 non-null  float64
dtypes: float64(7), int64(10), object(22)
memory usage: 157.2+ MB

In [14]:
columns_df = df.columns
columns_df_df

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [22]:
df['시도명'] = df['시도명'].str.lstrip()
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19917773,대구통닭,통통치킨상인2호점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2.729012e+24,NaN,대구광역시 달서구 상화북로43길 74,704370.0,42806.0,NaN,1,NaN,128.546040,35.817554
1,19919475,빵마루,NaN,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,2.726011e+24,녹원아파트,대구광역시 수성구 무학로 187,706090.0,42183.0,NaN,1,NaN,128.628821,35.830867
2,19925178,오구피자,NaN,Q,음식,Q07,패스트푸드,Q07A01,피자전문,I56192,...,2.817011e+24,NaN,인천광역시 남구 미추홀대로 541,402200.0,22216.0,NaN,1,NaN,126.678585,37.445680
3,19907335,명진가마솥오곡밥,NaN,Q,음식,Q01,한식,Q01A16,보리밥전문,I56111,...,2.920012e+24,NaN,광주광역시 광산구 첨단중앙로170번길 17,506303.0,62274.0,NaN,1,NaN,126.842826,35.220843
4,19909700,이오쇠고기국밥,NaN,Q,음식,Q01,한식,Q01A05,해장국/감자탕,I56111,...,2.711016e+24,NaN,대구광역시 중구 달구벌대로 2222,700430.0,41951.0,NaN,NaN,NaN,128.606083,35.862251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528306,16314214,A모텔,NaN,O,숙박,O02,모텔/여관/여인숙,O02A01,모텔/여관/여인숙,I55112,...,2.714010e+24,NaN,대구광역시 동구 동부로22길 27,701827.0,41243.0,NaN,NaN,NaN,128.627103,35.874158
528307,16292329,하얀기쁨,NaN,F,생활서비스,F02,세탁/가사서비스,F02A01,세탁소/빨래방,S96912,...,3.020015e+24,더리치타운,대전광역시 유성구 관평1로 15,305509.0,34017.0,NaN,1,113,127.387018,36.425895
528308,16292506,쭈네일,NaN,F,생활서비스,F01,이/미용/건강,F01A02,발/네일케어,S96119,...,3.611010e+24,스타힐타워2,세종특별자치시 세종특별자치시 한누리대로 2129,339008.0,30150.0,2,NaN,2,127.289760,36.478573
528309,16394366,효소먹은돼지,NaN,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,2.920012e+24,NaN,광주광역시 광산구 풍영로200번길 13,506304.0,62225.0,NaN,NaN,NaN,126.815130,35.189369
528310,16335149,더칼라네일&속눈썹,NaN,F,생활서비스,F01,이/미용/건강,F01A02,발/네일케어,S96119,...,2.729011e+24,NaN,대구광역시 달서구 당산로 27,704912.0,42676.0,NaN,NaN,NaN,128.544277,35.839861

In [23]:
daegu =  df[df['시도명']== "대구광역시"]
daegu

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,19917773,대구통닭,통통치킨상인2호점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2.729012e+24,NaN,대구광역시 달서구 상화북로43길 74,704370.0,42806.0,NaN,1,NaN,128.546040,35.817554
1,19919475,빵마루,NaN,Q,음식,Q08,제과제빵떡케익,Q08A01,제과점,I56191,...,2.726011e+24,녹원아파트,대구광역시 수성구 무학로 187,706090.0,42183.0,NaN,1,NaN,128.628821,35.830867
4,19909700,이오쇠고기국밥,NaN,Q,음식,Q01,한식,Q01A05,해장국/감자탕,I56111,...,2.711016e+24,NaN,대구광역시 중구 달구벌대로 2222,700430.0,41951.0,NaN,NaN,NaN,128.606083,35.862251
11,19921253,미화,NaN,Q,음식,Q03,일식/수산물,Q03A20,복전문,I56111,...,2.711010e+24,NaN,대구광역시 중구 동덕로30길 57,700847.0,41945.0,NaN,1,2,128.606981,35.866834
12,19921284,충무회,NaN,Q,음식,Q03,일식/수산물,Q03A01,횟집,I56111,...,2.726011e+24,NaN,대구광역시 수성구 들안로2길 19,706801.0,42173.0,NaN,1,NaN,128.617649,35.831691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528303,16369125,동녘바다머구리해물,NaN,Q,음식,Q03,일식/수산물,Q03A05,해물찜/탕전문,I56111,...,2.726011e+24,NaN,대구광역시 수성구 들안로8길 5,706800.0,42173.0,NaN,NaN,NaN,128.617187,35.833532
528304,16368237,해녀조개돌문어탕,NaN,Q,음식,Q03,일식/수산물,Q03A05,해물찜/탕전문,I56111,...,2.726010e+24,NaN,대구광역시 수성구 수성로 346,706032.0,42125.0,NaN,NaN,NaN,128.614044,35.856478
528305,16372423,민영이수제돈까스,NaN,Q,음식,Q06,양식,Q06A02,돈가스전문점,I56114,...,2.729010e+24,두류종합상가,대구광역시 달서구 당산동길 9,704918.0,42654.0,NaN,1,134,128.545157,35.845499
528306,16314214,A모텔,NaN,O,숙박,O02,모텔/여관/여인숙,O02A01,모텔/여관/여인숙,I55112,...,2.714010e+24,NaN,대구광역시 동구 동부로22길 27,701827.0,41243.0,NaN,NaN,NaN,128.627103,35.874158
528310,16335149,더칼라네일&속눈썹,NaN,F,생활서비스,F01,이/미용/건강,F01A02,발/네일케어,S96119,...,2.729011e+24,NaN,대구광역시 달서구 당산로 27,704912.0,42676.0,NaN,NaN,NaN,128.544277,35.839861

In [25]:
daegu.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 129875 entries, 0 to 528310
Data columns (total 39 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     129875 non-null  int64
 1   상호명        129875 non-null  object
 2   지점명        15247 non-null   object
 3   상권업종대분류코드  129875 non-null  object
 4   상권업종대분류명   129875 non-null  object
 5   상권업종중분류코드  129875 non-null  object
 6   상권업종중분류명   129875 non-null  object
 7   상권업종소분류코드  129875 non-null  object
 8   상권업종소분류명   129875 non-null  object
 9   표준산업분류코드   122274 non-null  object
 10  표준산업분류명    122274 non-null  object
 11  시도코드       129875 non-null  int64
 12  시도명        129875 non-null  object
 13  시군구코드      129875 non-null  int64
 14  시군구명       129875 non-null  object
 15  행정동코드      129875 non-null  int64
 16  행정동명       129875 non-null  object
 17  법정동코드      129875 non-null  int64
 18  법정동명       129875 non-null  object
 19  지번코드       129875 non-null  int64
 20  대지구분코드     129875 non-null  int64
 21  대지구분명      129875 non-null  object
 22  지번본번지      129875 non-null  int64
 23  지번부번지      105295 non-null  float64
 24  지번주소       129875 non-null  object
 25  도로명코드      129875 non-null  int64
 26  도로명        129875 non-null  object
 27  건물본번지      129875 non-null  int64
 28  건물부번지      21715 non-null   float64
 29  건물관리번호     129875 non-null  float64
 30  건물명        30059 non-null   object
 31  도로명주소      129875 non-null  object
 32  구우편번호      129875 non-null  float64
 33  신우편번호      129865 non-null  float64
 34  동정보        13917 non-null   object
 35  층정보        47908 non-null   object
 36  호정보        21644 non-null   object
 37  경도         129875 non-null  float64
 38  위도         129875 non-null  float64
dtypes: float64(7), int64(10), object(22)
memory usage: 39.6+ MB

In [26]:
daegu.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [27]:
col_filtered = daegu[['상가업소번호','상호명','상권업종중분류명','시군구명','행정동명','지번주소','도로명주소','경도','위도']]
col_filtered

,상가업소번호,상호명,상권업종중분류명,시군구명,행정동명,지번주소,도로명주소,경도,위도
0,19917773,대구통닭,닭/오리요리,달서구,상인1동,대구광역시 달서구 상인동 1531-12,대구광역시 달서구 상화북로43길 74,128.546040,35.817554
1,19919475,빵마루,제과제빵떡케익,수성구,지산1동,대구광역시 수성구 지산동 761-8,대구광역시 수성구 무학로 187,128.628821,35.830867
4,19909700,이오쇠고기국밥,한식,중구,대봉1동,대구광역시 중구 대봉동 12-9,대구광역시 중구 달구벌대로 2222,128.606083,35.862251
11,19921253,미화,일식/수산물,중구,동인동,대구광역시 중구 동인동4가 248-20,대구광역시 중구 동덕로30길 57,128.606981,35.866834
12,19921284,충무회,일식/수산물,수성구,두산동,대구광역시 수성구 두산동 154-26,대구광역시 수성구 들안로2길 19,128.617649,35.831691
...,...,...,...,...,...,...,...,...,...
528303,16369125,동녘바다머구리해물,일식/수산물,수성구,두산동,대구광역시 수성구 두산동 138-14,대구광역시 수성구 들안로8길 5,128.617187,35.833532
528304,16368237,해녀조개돌문어탕,일식/수산물,수성구,수성2.3가동,대구광역시 수성구 수성동2가 238-3,대구광역시 수성구 수성로 346,128.614044,35.856478
528305,16372423,민영이수제돈까스,양식,달서구,성당동,대구광역시 달서구 성당동 704-5,대구광역시 달서구 당산동길 9,128.545157,35.845499
528306,16314214,A모텔,모텔/여관/여인숙,동구,신천4동,대구광역시 동구 신천동 325-7,대구광역시 동구 동부로22길 27,128.627103,35.874158
528310,16335149,더칼라네일&속눈썹,이/미용/건강,달서구,본리동,대구광역시 달서구 본리동 145-5,대구광역시 달서구 당산로 27,128.544277,35.839861

In [34]:
col_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 129875 entries, 0 to 528310
Data columns (total 9 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   상가업소번호    129875 non-null  int64
 1   상호명       129875 non-null  object
 2   상권업종중분류명  129875 non-null  object
 3   시군구명      129875 non-null  object
 4   행정동명      129875 non-null  object
 5   지번주소      129875 non-null  object
 6   도로명주소     129875 non-null  object
 7   경도        129875 non-null  float64
 8   위도        129875 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 9.9+ MB

In [55]:
cafe_df = col_filtered[col_filtered['상권업종중분류명']=="커피점/카페"]
cafe_df

,상가업소번호,상호명,상권업종중분류명,시군구명,행정동명,지번주소,도로명주소,경도,위도
116,20923824,브라운,커피점/카페,수성구,고산2동,대구광역시 수성구 노변동 353,대구광역시 수성구 노변로 55,128.699230,35.835111
627,22699925,카페신라,커피점/카페,중구,성내1동,대구광역시 중구 동문동 20-4,대구광역시 중구 경상감영길 171,128.596926,35.872581
705,22852327,미도,커피점/카페,중구,성내2동,대구광역시 중구 종로2가 66-1,대구광역시 중구 중앙대로77길 19,128.592485,35.868132
1006,25347698,썸,커피점/카페,북구,읍내동,대구광역시 북구 읍내동 1236-47,대구광역시 북구 칠곡중앙대로 614-29,128.554131,35.949804
1018,25504085,까치찻집,커피점/카페,수성구,지산1동,대구광역시 수성구 지산동 1277-19,대구광역시 수성구 지범로 145,128.636445,35.823590
...,...,...,...,...,...,...,...,...,...
527946,16360946,미메이트커피,커피점/카페,달서구,상인1동,대구광역시 달서구 상인동 926,대구광역시 달서구 송현로7안길 16,128.547417,35.818332
528017,16364456,미쁜과일,커피점/카페,동구,신암1동,대구광역시 동구 신암동 738-3,대구광역시 동구 아양로 37-5,128.618610,35.882701
528039,16318876,커맥스,커피점/카페,수성구,수성4가동,대구광역시 수성구 수성동4가 1090-8,대구광역시 수성구 수성로 393,128.613094,35.861161
528041,16318708,마커스커피컴퍼니,커피점/카페,수성구,고산2동,대구광역시 수성구 시지동 485-1,대구광역시 수성구 시지로 14-3,128.692078,35.841254
528264,16365855,몬스터커피,커피점/카페,북구,침산3동,대구광역시 북구 침산동 269-10,대구광역시 북구 침산로 153,128.590613,35.888890

In [56]:
cafe_df.head()

,상가업소번호,상호명,상권업종중분류명,시군구명,행정동명,지번주소,도로명주소,경도,위도
116,20923824,브라운,커피점/카페,수성구,고산2동,대구광역시 수성구 노변동 353,대구광역시 수성구 노변로 55,128.699230,35.835111
627,22699925,카페신라,커피점/카페,중구,성내1동,대구광역시 중구 동문동 20-4,대구광역시 중구 경상감영길 171,128.596926,35.872581
705,22852327,미도,커피점/카페,중구,성내2동,대구광역시 중구 종로2가 66-1,대구광역시 중구 중앙대로77길 19,128.592485,35.868132
1006,25347698,썸,커피점/카페,북구,읍내동,대구광역시 북구 읍내동 1236-47,대구광역시 북구 칠곡중앙대로 614-29,128.554131,35.949804
1018,25504085,까치찻집,커피점/카페,수성구,지산1동,대구광역시 수성구 지산동 1277-19,대구광역시 수성구 지범로 145,128.636445,35.823590

In [66]:
cafe_df1 = cafe_df.drop_duplicates(['상가업소번호','지번주소'],keep='first')
cafe_df1

,상가업소번호,상호명,상권업종중분류명,시군구명,행정동명,지번주소,도로명주소,경도,위도
116,20923824,브라운,커피점/카페,수성구,고산2동,대구광역시 수성구 노변동 353,대구광역시 수성구 노변로 55,128.699230,35.835111
627,22699925,카페신라,커피점/카페,중구,성내1동,대구광역시 중구 동문동 20-4,대구광역시 중구 경상감영길 171,128.596926,35.872581
705,22852327,미도,커피점/카페,중구,성내2동,대구광역시 중구 종로2가 66-1,대구광역시 중구 중앙대로77길 19,128.592485,35.868132
1006,25347698,썸,커피점/카페,북구,읍내동,대구광역시 북구 읍내동 1236-47,대구광역시 북구 칠곡중앙대로 614-29,128.554131,35.949804
1018,25504085,까치찻집,커피점/카페,수성구,지산1동,대구광역시 수성구 지산동 1277-19,대구광역시 수성구 지범로 145,128.636445,35.823590
...,...,...,...,...,...,...,...,...,...
527946,16360946,미메이트커피,커피점/카페,달서구,상인1동,대구광역시 달서구 상인동 926,대구광역시 달서구 송현로7안길 16,128.547417,35.818332
528017,16364456,미쁜과일,커피점/카페,동구,신암1동,대구광역시 동구 신암동 738-3,대구광역시 동구 아양로 37-5,128.618610,35.882701
528039,16318876,커맥스,커피점/카페,수성구,수성4가동,대구광역시 수성구 수성동4가 1090-8,대구광역시 수성구 수성로 393,128.613094,35.861161
528041,16318708,마커스커피컴퍼니,커피점/카페,수성구,고산2동,대구광역시 수성구 시지동 485-1,대구광역시 수성구 시지로 14-3,128.692078,35.841254
528264,16365855,몬스터커피,커피점/카페,북구,침산3동,대구광역시 북구 침산동 269-10,대구광역시 북구 침산로 153,128.590613,35.888890

In [68]:
all_names = pd.Series(cafe_df1.상호명.unique())
all_names

0            브라운
1           카페신라
2             미도
3              썸
4           까치찻집
          ...
3338        꼬모맨션
3339      미메이트커피
3340        미쁜과일
3341         커맥스
3342    마커스커피컴퍼니
Length: 3343, dtype: object

In [69]:
search_cafe_starbucks = all_names[all_names.str.contains('스타벅스')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [ ]:
search_cafe_starbucks

In [70]:
cafe_unique_ediya = pd.Series(cafe_df.상호명)
cafe_ediya = cafe_unique_ediya[cafe_unique_ediya.str.contains('이디야')]
cafe_ediya

ValueError: Cannot mask with non-boolean array containing NA / NaN values